# OpenRewrite Runner with automatic PR creation
# This example runs recipes and creates a pull request with the changes

name: OpenRewrite with PR

on:
  workflow_dispatch:
    inputs:
      recipes:
        description: 'Comma-separated recipe names'
        required: true
      recipe-parameters:
        description: 'Recipe parameters (recipeName.paramName=value)'
        required: false

jobs:
  run-openrewrite:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run OpenRewrite
        id: openrewrite
        uses: rhart/openrewrite-runner-action@main
        with:
          recipes: ${{ github.event.inputs.recipes }}
          recipe-parameters: ${{ github.event.inputs.recipe-parameters }}
          recipes-dir: "recipes"
          rewrite-dependencies: "org.openrewrite:rewrite-yaml:8.66.3"

      - name: Create Pull Request
        if: steps.openrewrite.outputs.changes-detected == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Apply OpenRewrite recipes ${{ github.event.inputs.recipes }}'
          title: 'OpenRewrite: Apply recipes ${{ github.event.inputs.recipes }}'
          body: |
            This PR was automatically generated by OpenRewrite.

            **Recipes applied:** `${{ steps.openrewrite.outputs.activated-recipes }}`

            Please review the changes carefully before merging.
          branch: openrewrite-auto-pr
          delete-branch: true
          labels: automated,openrewrite

      - name: No changes detected
        if: steps.openrewrite.outputs.changes-detected == 'false'
        run: |
          echo "No changes were made by OpenRewrite. Nothing to commit."
